Integration
karmaester/react-calculator pull request #4
Opened 2021-05-03 14:13 UTC by karmaester

Add calculate method in App.js

Pass handleClick as prop to ButtonPanel

2021-05-03 14:42 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @karmaester, congratulations on this milestone :fireworks: We are almost done with this milestone :muscle: The right linter files were used, README file and code is clean. However, we are left with a few comments to address in the comments below:


Once these are addressed, kindly submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

2021-05-03 14:42 UTC, addod19 commented on src/components/App.js
> +const App = () => {
Our aim is to convert this functional component to a class component, initialize the state in the constructor, implement handleClick in the constructor.......Kindly make this change

2021-05-03 14:42 UTC, addod19 commented on src/components/ButtonPanel.js
>        {nums1.map((num) => (
Kindly implement the handleClick function in the ButtonPanel component, instead of passing it down from the parent component

2021-05-04 00:03 UTC, arslanbisharat approved these changes
# Approved :clap:

Hello Developer :wave:

Thank You for submitting this Pull Request. I am thrilled to inform you that your project is approved now. :clap:

You have done a great job. I like your project. 

**To highlight** 

- [ ] You have a descriptive Readme. Nice Job. 
- [ ] Your Pull Request is nice. Good Job!
- [ ] You are using linters and no error is present. I am happy to see it. 
- [ ] Your project has met the minimum technical requirements too. 



In short, I am very excited to see this project and proud of you. 

**What to do next?** :thinking:

1- Visit https://dashboard.microverse.org/projects and submit your approved project. 
2- Prepare yourself for the next project. 

I am wishing you very good luck with the next project. :smile:

Once again, Congratulations!:joy:

**Best,
Arslan Bisharat(PT-TSE)
Slack: @arslanbisharat**

2021-05-04 03:32 UTC, merged